### PR TITLE
Generalize ``get_dummies``

### PR DESCRIPTION
**Pull request by rjzamora**
- Generalizes `get_dummies`/`GetDummies` to work with `cudf`
- Fixes a minor bug (missing `"sparse"` parameter)

### CODE REVIEW

**Comment by phofl** [comment]
I suppose we can't add a test here?

**Comment by rjzamora** [comment]
>I suppose we can't add a test here?

This is a good question. I updated the test to work with both pandas and cudf.

Not sure if we want to add test coverage for the parameters?

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
I think that's fine, it would be covered by the gpu ci, correct?

**Comment by phofl** [comment]
thx

**Comment by rjzamora** [comment]
>it would be covered by the gpu ci, correct?

I'm working on this :)

**Pull request merged**
